version: '3'

#自定义redis base images
#部署需要更换REDIS_ADDR地址，必须bind内网地址
#可以横行扩展scale

services:
  redis_1001:
    image: "jackeylov3/redis-demo"
    restart: always
    privileged: true
    volumes:
      - /data/control/devops/redis_cluster/redis_1001/data:/data
    environment:
      REDIS_PORT: 1001
      REDIS_ADDR: '127.0.0.1'
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["nohup","redis-server","/etc/redis/redis.conf"]
    network_mode: "host"

  redis_1002:
    image: "jackeylov3/redis-demo"
    restart: always
    privileged: true
    volumes:
      - /data/control/devops/redis_cluster/redis_1002/data:/data
    environment:
      REDIS_PORT: 1002
      REDIS_ADDR: '127.0.0.1'
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["nohup","redis-server","/etc/redis/redis.conf"]
    network_mode: "host"

  redis_1003:
    image: "jackeylov3/redis-demo"
    restart: always
    privileged: true
    volumes:
      - /data/control/devops/redis_cluster/redis_1003/data:/data
    environment:
      REDIS_PORT: 1003
      REDIS_ADDR: '127.0.0.1'
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["nohup","redis-server","/etc/redis/redis.conf"]
    network_mode: "host"

  redis_1004:
    image: "jackeylov3/redis-demo"
    restart: always
    privileged: true
    volumes:
      - /data/control/devops/redis_cluster/redis_1004/data:/data
    environment:
      REDIS_PORT: 1004
      REDIS_ADDR: '127.0.0.1'
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["nohup","redis-server","/etc/redis/redis.conf"]
    network_mode: "host"

  redis_1005:
    image: "jackeylov3/redis-demo"
    restart: always
    privileged: true
    volumes:
      - /data/control/devops/redis_cluster/redis_1005/data:/data
    environment:
      REDIS_PORT: 1005
      REDIS_ADDR: '127.0.0.1'
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["nohup","redis-server","/etc/redis/redis.conf"]
    network_mode: "host"

  redis_1006:
    image: "jackeylov3/redis-demo"
    restart: always
    privileged: true
    volumes:
      - /data/control/devops/redis_cluster/redis_1006/data:/data
    environment:
      REDIS_PORT: 1006
      REDIS_ADDR: '127.0.0.1'
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["nohup","redis-server","/etc/redis/redis.conf"]
    network_mode: "host"
